#!/usr/bin/env python

Import("env")
Import("env_modules")

env_compositor = env_modules.Clone()
env_compositor.Prepend(CPPPATH=["."])

# Godot's own source files
env_compositor.add_source_files(env.modules_sources, "*.cpp")
