#!/usr/bin/env python

Import("env")
Import("env_modules")

env_eoe = env_modules.Clone()
env_eoe.add_source_files(env.modules_sources, "*.cpp")
env_eoe.add_source_files(env.modules_sources, "np_dialog/*.cpp")
env_eoe.add_source_files(env.modules_sources, "np_dialog/import/*.cpp")
